name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual run"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Toolchain
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: Install
        run: |
          go install gotest.tools/gotestsum@latest

      - name: Test
        run: |
          make test

      - name: Format
        run: cargo fmt --check
